### ISSUE TITLE
Error while running `mix churn`

### ISSUE THREAD

**Issue by tomekowal** [patrykwozinski/churn#15]
Hey! Thanks for awesome project!

```
** (SyntaxError) nofile:1: syntax error before: '='
    lib/churn/processor/cyclomatic_complexity.ex:13: Churn.Processor.CyclomaticComplexity.calculate/1
    lib/churn/processor.ex:11: Churn.Processor.process/2
    (elixir 1.10.4) lib/stream.ex:572: anonymous fn/4 in Stream.map/2
    (elixir 1.10.4) lib/enum.ex:3686: Enumerable.List.reduce/3
    (elixir 1.10.4) lib/stream.ex:1609: Enumerable.Stream.do_each/4
    (elixir 1.10.4) lib/enum.ex:3383: Enum.reverse/1
    (elixir 1.10.4) lib/enum.ex:2982: Enum.to_list/1
```

I am in an umbrella app and using default config except I've changed `lib` to `apps`. If I change the value to `apps/*/lib` or `apps/*/test` it works OK.

**Comment by patrykwozinski** [comment]
Thanks! I have added this to `apps/*/lib` to the default configuration and every documentation page in the project. The interesting thing for me is that the error occurred but only for some of my umbrellas. I need to investigate it deeper.
